name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/kangwifi/kangwifios:latest
      options: --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
      
    steps:
    - name: Download ngrok
      run: apt update && apt install wget && wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    
    - name: Extract ngrok
      run: tar -xzf ngrok.tgz
    
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh  # Instalasi Ollama menggunakan curl

    - name: Install Podman and Docker CLI
      run: |
        apt-get install -y podman docker.io  # Instalasi Podman dan Docker CLI
    - name: Verify Podman and Docker CLI Installation
      run: |
        podman --version
        docker --version
        
    - name: Connect Docker CLI to Host Daemon
      run: |
        export DOCKER_HOST=unix:///var/run/docker.sock
        echo "DOCKER_HOST=unix:///var/run/docker.sock" >> ~/.bashrc

    - name: Setup SSH
      run: |
        apt-get install -y openssh-server
        # Generate SSH host keys
        ssh-keygen -A
        # Configure SSH
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config  # Pastikan autentikasi password diizinkan
        # Set password root dengan cara yang lebih eksplisit
        echo "root:1234" | chpasswd
        # Verifikasi password di-set
        grep root /etc/shadow
        # Start SSH daemon
        /usr/sbin/sshd -D &
    
    - name: Check SSH Status
      run: |
        sleep 5  # Tunggu sebentar agar sshd mulai
        ps aux | grep sshd || echo "SSHD not running"
        netstat -tuln | grep 22 || echo "Port 22 not open"
    
    - name: Create Tunnel
      run: |
        ./ngrok tcp 22 &  # Jalankan ngrok di background
        sleep 5  # Tunggu ngrok mulai
        # Tampilkan URL tunnel
        curl -s http://localhost:4040/api/tunnels | grep -o "tcp://[^\"]*"

    - name: Keep Alive
      run: |
        echo "SSH tunnel is running. Connect using the ngrok URL above."
        ollama serve
        sleep 360000  # Jaga tunnel hidup selama 1 jam
