name: Kangwifios CI (Container-based)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Update APT & Install Docker CLI
      run: |
        apt update
        apt-get update
        apt-get install -y docker.io openssh-server wget curl tar gnupg ca-certificates

    - name: Setup SSH Root Login
      run: |
        ssh-keygen -A
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
        echo "root:root" | chpasswd
        /usr/sbin/sshd
        echo "SSH Server Started"

    - name: Connect Docker CLI to Host Daemon
      run: |
        export DOCKER_HOST=unix:///var/run/docker.sock
        echo "DOCKER_HOST=unix:///var/run/docker.sock" >> ~/.bashrc

    - name: Download Ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract Ngrok & Authenticate
      run: |
        tar -xzf ngrok.tgz
        ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose Port 22 via Ngrok
      id: tunnel
      run: |
        ./ngrok tcp 22 > /dev/null &
        sleep 6
        tunnel_url=$(curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^\"]*')
        clean_url=${tunnel_url#tcp://}
        echo "ngrok_url=$clean_url" >> $GITHUB_OUTPUT

    - name: Show SSH Access Info
      run: |
        echo "=============================="
        echo "SSH Available at:"
        echo "ssh root@${{ steps.tunnel.outputs.ngrok_url }}"
        echo "Password: root"
        echo "=============================="

    - name: Test Docker Access
      run: |
        echo "Testing Docker inside the container:"
        docker ps || echo "Docker CLI installed but access failed"

    - name: Keep Alive
      run: |
        echo "Container running. Waiting for connections..."
        sleep 360000

