name: Kangwifios CI (Container-based)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update APT & Install Docker CLI
      shell: bash
      run: |
        sudo sed -i 's|http://archive.ubuntu.com|http://mirrors.edge.kernel.org|' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y docker.io openssh-server wget curl tar gnupg ca-certificates

    - name: Setup SSH Root Login
      shell: bash
      run: |
        sudo ssh-keygen -A
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "root:root" | sudo chpasswd
        sudo /usr/sbin/sshd
        echo "SSH Server Started"

    - name: Download Ngrok
      shell: bash
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
        tar -xzf ngrok.tgz

    - name: Authenticate Ngrok
      shell: bash
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose Port 22 via Ngrok
      id: tunnel
      shell: bash
      run: |
        ./ngrok tcp 22 > ngrok.log &
        sleep 10
        tunnel_url=$(curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^\"]*')
        clean_url=${tunnel_url#tcp://}
        echo "ngrok_url=$clean_url" >> $GITHUB_OUTPUT

    - name: Show SSH Access Info
      shell: bash
      run: |
        echo "=============================="
        echo "SSH Available at:"
        echo "ssh root@${{ steps.tunnel.outputs.ngrok_url }}"
        echo "Password: root"
        echo "=============================="

    - name: Test Docker Access
      shell: bash
      run: |
        echo "Testing Docker inside the container:"
        docker ps || echo "Docker CLI installed but access failed"

    - name: Keep Alive
      shell: bash
      run: |
        echo "Container running. Waiting for connections..."
        sleep 360000
